%% bootstrap_acados_windows_msvc_pure_matlab.m
% Pure MATLAB bootstrap for the local acados Windows/MSVC workflow.
%
% Place THIS FILE in the acados repository root and run:
%
%     bootstrap_acados_windows_msvc_pure_matlab
%
% This version uses MATLAB only.
% It does NOT call Python and does NOT contain encoded/base64 data.
%
% What it does
% ------------
% 1. Creates every *.in2.* file from the CURRENT upstream template file.
% 2. Patches MATLAB template selectors to use the *.in2.* files.
% 3. Patches Python template selectors too, because Python-generated solvers
%    should use the same Windows/MSVC templates.
% 4. Applies the MATLAB JSON/reuse fixes.
% 5. Patches Python CMakeBuilder for Visual Studio 2022 x64.
% 6. Generates:
%       acados_install_windows_msvc.m
%       acados_install_shared_and_static_windows_msvc.m
%    from the CURRENT upstream Windows installer files.
% 7. Writes a simple manifest text file.
%
% Safety
% ------
% - Original template files (*.in.m, CMakeLists.in.txt) are never modified.
% - Source/interface files are backed up once before editing.
% - If an expected upstream block cannot be found, the script stops instead
%   of guessing.
%
% This script is intentionally verbose and readable so that every change is
% visible and can be maintained later.

clearvars;
clc;

fprintf('============================================================\n');
fprintf(' acados Windows/MSVC PURE MATLAB bootstrap\n');
fprintf('============================================================\n\n');

%% ========================================================================
% 0. Locate acados root
% =========================================================================

bootstrap_file = mfilename('fullpath');

if isempty(bootstrap_file)
    error('Save this script before running it.');
end

acados_root = fileparts(bootstrap_file);

if ~isfile(fullfile(acados_root, 'CMakeLists.txt')) || ...
        ~isfolder(fullfile(acados_root, 'interfaces'))
    error(['Place this script in the acados repository root.\n', ...
           'Current script directory:\n  %s'], acados_root);
end

fprintf('acados root:\n  %s\n\n', acados_root);

matlab_dir = fullfile( ...
    acados_root, ...
    'interfaces', ...
    'acados_matlab_octave');

python_dir = fullfile( ...
    acados_root, ...
    'interfaces', ...
    'acados_template', ...
    'acados_template');

tera_dir = fullfile( ...
    python_dir, ...
    'c_templates_tera');

matlab_template_dir = fullfile( ...
    tera_dir, ...
    'matlab_templates');


%% ========================================================================
% 1. Derive *.in2.* files from CURRENT upstream templates
% =========================================================================

fprintf('[1/6] Deriving *.in2.* files from current upstream templates\n');

derive_cmake_template( ...
    fullfile(tera_dir, 'CMakeLists.in.txt'), ...
    fullfile(tera_dir, 'CMakeLists.in2.txt'));

derive_make_mex_template( ...
    fullfile(matlab_template_dir, 'make_mex.in.m'), ...
    fullfile(matlab_template_dir, 'make_mex.in2.m'), ...
    'ocp');

derive_make_mex_template( ...
    fullfile(matlab_template_dir, 'make_mex_sim.in.m'), ...
    fullfile(matlab_template_dir, 'make_mex_sim.in2.m'), ...
    'sim');

derive_make_sfun_template( ...
    fullfile(matlab_template_dir, 'make_sfun.in.m'), ...
    fullfile(matlab_template_dir, 'make_sfun.in2.m'));

derive_make_sfun_sim_template( ...
    fullfile(matlab_template_dir, 'make_sfun_sim.in.m'), ...
    fullfile(matlab_template_dir, 'make_sfun_sim.in2.m'));

derive_mex_sim_solver_template( ...
    fullfile(matlab_template_dir, 'mex_sim_solver.in.m'), ...
    fullfile(matlab_template_dir, 'mex_sim_solver.in2.m'));

fprintf('\n');


%% ========================================================================
% 2. Patch MATLAB template selectors
% =========================================================================

fprintf('[2/6] Patching MATLAB template selectors\n');

patch_matlab_ocp(fullfile(matlab_dir, 'AcadosOcp.m'));
patch_matlab_sim(fullfile(matlab_dir, 'AcadosSim.m'));

fprintf('\n');


%% ========================================================================
% 3. Patch Python template selectors
% =========================================================================

fprintf('[3/6] Patching Python template selectors\n');

patch_python_ocp(fullfile(python_dir, 'acados_ocp.py'));
patch_python_sim(fullfile(python_dir, 'acados_sim.py'));

fprintf('\n');


%% ========================================================================
% 4. Patch Python CMakeBuilder for Visual Studio 2022 x64
% =========================================================================

fprintf('[4/6] Patching Python CMakeBuilder\n');

patch_python_builder(fullfile(python_dir, 'builders.py'));

fprintf('\n');


%% ========================================================================
% 5. Apply MATLAB JSON/reuse fixes
% =========================================================================

fprintf('[5/6] Applying MATLAB JSON/reuse fixes\n');

patch_compare_struct_to_json( ...
    fullfile(matlab_dir, 'compare_struct_to_json.m'));

patch_acados_sim_options( ...
    fullfile(matlab_dir, 'AcadosSimOptions.m'));

patch_acados_sim_solver( ...
    fullfile(matlab_dir, 'AcadosSimSolver.m'));

patch_acados_sim_to_struct( ...
    fullfile(matlab_dir, 'AcadosSim.m'));

patch_acados_codegen_options( ...
    fullfile(matlab_dir, 'AcadosCodeGenOptions.m'));

patch_acados_ocp_solver( ...
    fullfile(matlab_dir, 'AcadosOcpSolver.m'));

fprintf('\n');


%% ========================================================================
% 6. Generate MSVC installer helpers from CURRENT upstream installers
% =========================================================================

fprintf('[6/6] Deriving MSVC installer helpers\n');

derive_msvc_installer( ...
    fullfile(matlab_dir, 'acados_install_windows.m'), ...
    fullfile(matlab_dir, 'acados_install_windows_msvc.m'));

derive_shared_static_msvc_installer( ...
    fullfile(matlab_dir, 'acados_install_shared_and_static_windows.m'), ...
    fullfile(matlab_dir, 'acados_install_shared_and_static_windows_msvc.m'));

write_manifest(acados_root);

fprintf('\n============================================================\n');
fprintf(' Bootstrap completed successfully\n');
fprintf('============================================================\n\n');

fprintf('Generated/updated:\n');
fprintf('  *.in2.* templates\n');
fprintf('  MATLAB + Python selector patches\n');
fprintf('  JSON/reuse fixes\n');
fprintf('  MSVC installer helpers\n');
fprintf('  .acados_windows_msvc_patch_manifest.txt\n\n');

fprintf('Next:\n');
fprintf('  1. Restart MATLAB if this checkout was already loaded.\n');
fprintf('  2. Verify getenv(''ACADOS_INSTALL_DIR'') and which AcadosOcp -all.\n');
fprintf('  3. Run acados_install_shared_and_static_windows_msvc(...).\n');
fprintf('  4. Delete old generated_solver/generated_sim before the first clean test.\n');


%% ========================================================================
% Local functions
% =========================================================================

function derive_cmake_template(src, dst)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    old_expr = [ ...
        '    {%- set link_libs = code_gen_options.acados_link_libs.qpoases ~ " " ~ ', ...
        'code_gen_options.acados_link_libs.hpmpc ~ " " ~ ', ...
        'code_gen_options.acados_link_libs.osqp ~ " " ~ ', ...
        'code_gen_options.acados_link_libs.daqp ~ " " ~ ', ...
        'code_gen_options.acados_link_libs.clarabel -%}' ...
    ];

    if ~contains(txt, 'code_gen_options.acados_link_libs.qpdunes')

        new_expr = [ ...
            '    {# WINDOWS/MSVC PATCH: include qpDUNES in generated solver linking. #}', newline, ...
            '    {%- set link_libs = code_gen_options.acados_link_libs.qpoases ~ " " ~ ', ...
            'code_gen_options.acados_link_libs.hpmpc ~ " " ~ ', ...
            'code_gen_options.acados_link_libs.osqp ~ " " ~ ', ...
            'code_gen_options.acados_link_libs.qpdunes ~ " " ~ ', ...
            'code_gen_options.acados_link_libs.daqp ~ " " ~ ', ...
            'code_gen_options.acados_link_libs.clarabel -%}' ...
        ];

        txt = replace_once( ...
            txt, ...
            old_expr, ...
            new_expr, ...
            'CMake qpDUNES link expression');
    end

    old_block = strjoin({ ...
        '# link to libraries', ...
        'if(UNIX)', ...
        '    set(ACADOS_LINK_LIBS acados hpipm blasfeo m {{ link_libs }} CACHE STRING "Define what libs to link with acados solver")', ...
        'else()', ...
        '    set(ACADOS_LINK_LIBS acados hpipm blasfeo {{ link_libs }} CACHE STRING "Define what libs to link with acados solver")', ...
        'endif()', ...
        '', ...
        'link_libraries(${ACADOS_LINK_LIBS})' ...
    }, newline);

    new_block = strjoin({ ...
        '# link to libraries', ...
        'if(UNIX)', ...
        '    set(_ACADOS_DEFAULT_LINK_LIBS', ...
        '        acados hpipm blasfeo m {{ link_libs }})', ...
        'else()', ...
        '    set(_ACADOS_DEFAULT_LINK_LIBS', ...
        '        acados hpipm blasfeo {{ link_libs }})', ...
        'endif()', ...
        '', ...
        '###############################################################################', ...
        '# WINDOWS/MSVC PATCH:', ...
        '# Normalize GNU-style -l<name> linker arguments for native MSVC.', ...
        '###############################################################################', ...
        'if(MSVC)', ...
        '    set(_ACADOS_MSVC_LINK_LIBS "")', ...
        '', ...
        '    foreach(_lib IN LISTS _ACADOS_DEFAULT_LINK_LIBS)', ...
        '        string(REGEX REPLACE "^-l" "" _normalized_lib "${_lib}")', ...
        '        list(APPEND _ACADOS_MSVC_LINK_LIBS "${_normalized_lib}")', ...
        '    endforeach()', ...
        '', ...
        '    set(_ACADOS_DEFAULT_LINK_LIBS "${_ACADOS_MSVC_LINK_LIBS}")', ...
        'endif()', ...
        '', ...
        'set(', ...
        '    ACADOS_LINK_LIBS', ...
        '    "${_ACADOS_DEFAULT_LINK_LIBS}"', ...
        '    CACHE STRING', ...
        '    "Define what libs to link with acados solver"', ...
        ')', ...
        '', ...
        'link_libraries(${ACADOS_LINK_LIBS})' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old_block, ...
        new_block, ...
        'CMake MSVC link normalization');

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function derive_make_mex_template(src, dst, solver_kind)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    old = "    template_lib_path = ['-L' fullfile(pwd)];";

    if strcmp(solver_kind, 'ocp')
        solver_prefix = 'acados_ocp_solver_';
        warning_id = 'acados:make_mex:copyArtifact';
    else
        solver_prefix = 'acados_sim_solver_';
        warning_id = 'acados:make_mex_sim:copyArtifact';
    end

    lib_patch = strjoin({ ...
        '    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '    % WINDOWS/MSVC PATCH: CMake multi-config library location', ...
        '    %', ...
        '    % Visual Studio may place the problem-specific import library in a', ...
        '    % nested Release directory. Search recursively as a fallback.', ...
        ['    solver_lib_name = [''', solver_prefix, '{{ name }}.lib''];'], ...
        '    solver_lib_file = fullfile(pwd, solver_lib_name);', ...
        '', ...
        '    if isfile(solver_lib_file)', ...
        '        lib_dir = pwd;', ...
        '    else', ...
        '        d = dir(fullfile(pwd, ''**'', solver_lib_name));', ...
        '        if ~isempty(d)', ...
        '            lib_dir = d(1).folder;', ...
        '        else', ...
        '            lib_dir = pwd;', ...
        '        end', ...
        '    end', ...
        '', ...
        '    template_lib_path = [''-L'' lib_dir];', ...
        '    % END WINDOWS/MSVC PATCH', ...
        '    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        char(old), ...
        lib_patch, ...
        [solver_kind, ' make_mex library search']);

    final_end = find_final_function_end(txt);

    artifact_patch = strjoin({ ...
        '', ...
        '    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '    % WINDOWS/MSVC PATCH: collect problem-specific artifacts beside the', ...
        '    % generated MEX wrappers.', ...
        '    if ispc', ...
        '        dest_dir = pwd;', ...
        '        patterns = { ...', ...
        ['            ''', solver_prefix, '{{ name }}.dll'', ...'], ...
        ['            ''', solver_prefix, '{{ name }}.lib'', ...'], ...
        ['            ''', solver_prefix, '{{ name }}.exp'' ...'], ...
        '        };', ...
        '', ...
        '        for k = 1:numel(patterns)', ...
        '            dst_artifact = fullfile(dest_dir, patterns{k});', ...
        '', ...
        '            if isfile(dst_artifact)', ...
        '                continue;', ...
        '            end', ...
        '', ...
        '            matches = dir(fullfile(pwd, ''**'', patterns{k}));', ...
        '            if ~isempty(matches)', ...
        '                src_artifact = fullfile(matches(1).folder, matches(1).name);', ...
        '                try', ...
        '                    copyfile(src_artifact, dst_artifact, ''f'');', ...
        '                catch ME', ...
        ['                    warning(''', warning_id, ''', ...'], ...
        '                        ''Could not copy %s to code export directory: %s'', ...', ...
        '                        patterns{k}, ME.message);', ...
        '                end', ...
        '            end', ...
        '        end', ...
        '    end', ...
        '    % END WINDOWS/MSVC PATCH', ...
        '    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '' ...
    }, newline);

    txt = [ ...
        txt(1:final_end-1), ...
        artifact_patch, ...
        txt(final_end:end) ...
    ];

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function derive_make_sfun_template(src, dst)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    old_block = strjoin({ ...
        '% acados linking libraries and flags', ...
        '{%- if code_gen_options.acados_link_libs and code_gen_options.os and code_gen_options.os == "pc" %}', ...
        'LDFLAGS = [LDFLAGS '' {{ code_gen_options.acados_link_libs.openmp }}''];', ...
        'COMPFLAGS = [COMPFLAGS '' {{ code_gen_options.acados_link_libs.openmp }}''];', ...
        'LIBS{end+1} = ''{{ code_gen_options.acados_link_libs.qpoases }}'';', ...
        'LIBS{end+1} = ''{{ code_gen_options.acados_link_libs.hpmpc }}'';', ...
        'LIBS{end+1} = ''{{ code_gen_options.acados_link_libs.osqp }}'';', ...
        '{%- else %}', ...
        '    {% if solver_options.qp_solver is containing("QPOASES") %}', ...
        'LIBS{end+1} = ''-lqpOASES_e'';', ...
        '    {% endif %}', ...
        '    {% if solver_options.qp_solver is containing("DAQP") %}', ...
        'LIBS{end+1} = ''-ldaqp'';', ...
        '    {% endif %}', ...
        '{%- endif %}' ...
    }, newline);

    new_block = strjoin({ ...
        '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '% WINDOWS/MSVC PATCH: robust optional-library linking', ...
        '%', ...
        '% Read installed link_libs.json instead of hard-coding a small subset.', ...
        'acados_folder = getenv(''ACADOS_INSTALL_DIR'');', ...
        'link_libs_core_filename = fullfile(acados_folder, ''lib'', ''link_libs.json'');', ...
        '', ...
        'addpath(fullfile(acados_folder, ''external'', ''jsonlab''));', ...
        'link_libs = loadjson(link_libs_core_filename);', ...
        '', ...
        'acados_lib_extra = {};', ...
        'lib_names = fieldnames(link_libs);', ...
        '', ...
        'for idx = 1:numel(lib_names)', ...
        '    lib_name = lib_names{idx};', ...
        '    link_arg = link_libs.(lib_name);', ...
        '', ...
        '    if ~isempty(link_arg)', ...
        '        if strcmp(lib_name, ''openmp'')', ...
        '            if ~ismac()', ...
        '                LDFLAGS = [LDFLAGS, '' '', link_arg];', ...
        '                COMPFLAGS = [COMPFLAGS, '' '', link_arg];', ...
        '            end', ...
        '        else', ...
        '            acados_lib_extra{end+1} = link_arg;', ...
        '        end', ...
        '    end', ...
        'end', ...
        '% END WINDOWS/MSVC PATCH', ...
        '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old_block, ...
        new_block, ...
        'make_sfun optional-library block');

    old_mex = "            LIB_PATH, LIBS{:}, SOURCES{:}, ...";
    new_mex = "            LIB_PATH, LIBS{:}, acados_lib_extra{:}, SOURCES{:}, ...";

    txt = replace_once( ...
        txt, ...
        char(old_mex), ...
        char(new_mex), ...
        'make_sfun mex link arguments');

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function derive_make_sfun_sim_template(src, dst)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    marker = "LIBS = '-lacados -lhpipm -lblasfeo';";

    patch = strjoin({ ...
        char(marker), ...
        '', ...
        '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '% WINDOWS/MSVC PATCH: robust optional-library linking', ...
        'acados_folder = getenv(''ACADOS_INSTALL_DIR'');', ...
        'link_libs_core_filename = fullfile(acados_folder, ''lib'', ''link_libs.json'');', ...
        '', ...
        'addpath(fullfile(acados_folder, ''external'', ''jsonlab''));', ...
        'link_libs = loadjson(link_libs_core_filename);', ...
        '', ...
        'acados_lib_extra = {};', ...
        'lib_names = fieldnames(link_libs);', ...
        '', ...
        'for idx = 1:numel(lib_names)', ...
        '    lib_name = lib_names{idx};', ...
        '    link_arg = link_libs.(lib_name);', ...
        '', ...
        '    if ~isempty(link_arg)', ...
        '        if strcmp(lib_name, ''openmp'')', ...
        '            if ~ismac()', ...
        '                CFLAGS = [CFLAGS, '' '', link_arg];', ...
        '            end', ...
        '        else', ...
        '            acados_lib_extra{end+1} = link_arg;', ...
        '        end', ...
        '    end', ...
        'end', ...
        '', ...
        'if ~isempty(acados_lib_extra)', ...
        '    LIBS = [LIBS, '' '', strjoin(acados_lib_extra, '' '')];', ...
        'end', ...
        '% END WINDOWS/MSVC PATCH', ...
        '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        char(marker), ...
        patch, ...
        'make_sfun_sim optional-library block');

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function derive_mex_sim_solver_template(src, dst)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    old = strjoin({ ...
        '        % constructor', ...
        '        function obj = {{ name }}_mex_sim_solver()', ...
        '            make_mex_sim_{{ name }}();', ...
        '            obj.C_sim = acados_sim_create_{{ name }}();' ...
    }, newline);

    new = strjoin({ ...
        '        % constructor', ...
        '        function obj = {{ name }}_mex_sim_solver(varargin)', ...
        '', ...
        '            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '            % WINDOWS/MSVC PATCH: reuse problem-specific SIM MEX wrappers.', ...
        '            mex_create = fullfile(pwd, [''acados_sim_create_{{ name }}.'' mexext]);', ...
        '            mex_free   = fullfile(pwd, [''acados_sim_free_{{ name }}.'' mexext]);', ...
        '            mex_set    = fullfile(pwd, [''acados_sim_set_{{ name }}.'' mexext]);', ...
        '', ...
        '            mex_wrapper_missing = ...', ...
        '                ~isfile(mex_create) || ...', ...
        '                ~isfile(mex_free)   || ...', ...
        '                ~isfile(mex_set);', ...
        '', ...
        '            force_compile_mex_wrapper = false;', ...
        '', ...
        '            if nargin >= 1', ...
        '                solver_creation_opts = varargin{1};', ...
        '                if isstruct(solver_creation_opts) && ...', ...
        '                        isfield(solver_creation_opts, ''compile_mex_wrapper'')', ...
        '                    force_compile_mex_wrapper = ...', ...
        '                        solver_creation_opts.compile_mex_wrapper;', ...
        '                end', ...
        '            end', ...
        '', ...
        '            if force_compile_mex_wrapper', ...
        '                disp(''SIM MEX wrapper recompilation requested. Compiling...'');', ...
        '                make_mex_sim_{{ name }}();', ...
        '            elseif mex_wrapper_missing', ...
        '                disp(''SIM MEX wrapper missing. Compiling...'');', ...
        '                make_mex_sim_{{ name }}();', ...
        '            else', ...
        '                disp(''SIM MEX wrapper found. Reusing existing binaries.'');', ...
        '            end', ...
        '            % END WINDOWS/MSVC PATCH', ...
        '            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%', ...
        '', ...
        '            obj.C_sim = acados_sim_create_{{ name }}();' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old, ...
        new, ...
        'mex_sim_solver constructor');

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function patch_matlab_ocp(path)

    require_file(path);
    backup_once(path);

    patch_line_content( ...
        path, ...
        "template_list{end+1} = {'CMakeLists.in.txt', ['CMakeLists.txt']};", ...
        "template_list{end+1} = {'CMakeLists.in2.txt', ['CMakeLists.txt']};", ...
        '%', ...
        'MATLAB OCP CMake template');

    patch_line_content( ...
        path, ...
        "template_list{end+1} = {fullfile(matlab_template_path, 'make_mex.in.m'), ['make_mex_', self.name, '.m']};", ...
        "template_list{end+1} = {fullfile(matlab_template_path, 'make_mex.in2.m'), ['make_mex_', self.name, '.m']};", ...
        '%', ...
        'MATLAB OCP make_mex template');

    patch_line_content( ...
        path, ...
        "template_list{end+1} = {fullfile(matlab_template_path, 'make_sfun.in.m'), ['make_sfun.m']};", ...
        "template_list{end+1} = {fullfile(matlab_template_path, 'make_sfun.in2.m'), ['make_sfun.m']};", ...
        '%', ...
        'MATLAB OCP make_sfun template');

    patch_line_content( ...
        path, ...
        "template_list{end+1} = {fullfile(matlab_template_path, 'make_sfun_sim.in.m'), ['make_sfun_sim.m']};", ...
        "template_list{end+1} = {fullfile(matlab_template_path, 'make_sfun_sim.in2.m'), ['make_sfun_sim.m']};", ...
        '%', ...
        'MATLAB OCP make_sfun_sim template');
end


function patch_matlab_sim(path)

    require_file(path);
    backup_once(path);

    txt = fileread(path);

    if contains(txt, 'WINDOWS/MSVC PATCH: custom AcadosSim template selection')
        fprintf('  [already patched] MATLAB SIM template_list\n');
        return;
    end

    start_marker = '            % cell array with entries (template_file, output file)';
    end_marker = '            num_entries = length(template_list);';

    i0 = strfind(txt, start_marker);
    i1 = strfind(txt, end_marker);

    if isempty(i0) || isempty(i1)
        error('Could not locate AcadosSim template_list block.');
    end

    i0 = i0(1);
    i1 = i1(find(i1 > i0, 1, 'first'));

    block = strjoin({ ...
        '            % cell array with entries (template_file, output file)', ...
        '            %', ...
        '            % WINDOWS/MSVC PATCH: custom AcadosSim template selection', ...
        '            %', ...
        '            % Upstream -> local derivative:', ...
        '            %   mex_sim_solver.in.m -> mex_sim_solver.in2.m', ...
        '            %   make_mex_sim.in.m   -> make_mex_sim.in2.m', ...
        '            %   make_sfun_sim.in.m  -> make_sfun_sim.in2.m', ...
        '            %   CMakeLists.in.txt   -> CMakeLists.in2.txt', ...
        '            %', ...
        '            template_list = { ...', ...
        '                {''main_sim.in.c'', [''main_sim_'', self.name, ''.c'']}, ...', ...
        '                {fullfile(matlab_template_path, ''mex_sim_solver.in2.m''), [self.name, ''_mex_sim_solver.m'']}, ...', ...
        '                {fullfile(matlab_template_path, ''make_mex_sim.in2.m''), [''make_mex_sim_'', self.name, ''.m'']}, ...', ...
        '                {fullfile(matlab_template_path, ''acados_sim_create.in.c''), [''acados_sim_create_'', self.name, ''.c'']}, ...', ...
        '                {fullfile(matlab_template_path, ''acados_sim_free.in.c''), [''acados_sim_free_'', self.name, ''.c'']}, ...', ...
        '                {fullfile(matlab_template_path, ''acados_sim_set.in.c''), [''acados_sim_set_'', self.name, ''.c'']}, ...', ...
        '                {''acados_sim_solver.in.c'', [''acados_sim_solver_'', self.name, ''.c'']}, ...', ...
        '                {''acados_sim_solver.in.h'', [''acados_sim_solver_'', self.name, ''.h'']}, ...', ...
        '                {fullfile(matlab_template_path, ''acados_sim_solver_sfun.in.c''), [''acados_sim_solver_sfunction_'', self.name, ''.c'']}, ...', ...
        '                {fullfile(matlab_template_path, ''make_sfun_sim.in2.m''), [''make_sfun_sim_'', self.name, ''.m'']}, ...', ...
        '                {''Makefile.in'', ''Makefile''}, ...', ...
        '                {''CMakeLists.in2.txt'', ''CMakeLists.txt''}};', ...
        '', ...
        '' ...
    }, newline);

    txt = [txt(1:i0-1), block, txt(i1:end)];

    write_text_file(path, txt);

    fprintf('  [patched] MATLAB SIM template_list\n');
end


function patch_python_ocp(path)

    require_file(path);
    backup_once(path);

    patch_line_content( ...
        path, ...
        "template_list.append(('CMakeLists.in.txt', 'CMakeLists.txt'))", ...
        "template_list.append(('CMakeLists.in2.txt', 'CMakeLists.txt'))", ...
        '#', ...
        'Python OCP CMake template');

    patch_line_content( ...
        path, ...
        "template_file = os.path.join('matlab_templates', 'make_sfun.in.m')", ...
        "template_file = os.path.join('matlab_templates', 'make_sfun.in2.m')", ...
        '#', ...
        'Python OCP make_sfun template');

    patch_line_content( ...
        path, ...
        "template_file = os.path.join('matlab_templates', 'make_mex.in.m')", ...
        "template_file = os.path.join('matlab_templates', 'make_mex.in2.m')", ...
        '#', ...
        'Python OCP make_mex template');

    patch_line_content( ...
        path, ...
        "template_file = os.path.join('matlab_templates', 'make_sfun_sim.in.m')", ...
        "template_file = os.path.join('matlab_templates', 'make_sfun_sim.in2.m')", ...
        '#', ...
        'Python OCP make_sfun_sim template');
end


function patch_python_sim(path)

    require_file(path);
    backup_once(path);

    patch_line_content( ...
        path, ...
        "template_list.append(('CMakeLists.in.txt', 'CMakeLists.txt'))", ...
        "template_list.append(('CMakeLists.in2.txt', 'CMakeLists.txt'))", ...
        '#', ...
        'Python SIM CMake template');

    patch_line_content( ...
        path, ...
        "template_file = os.path.join('matlab_templates', 'mex_sim_solver.in.m')", ...
        "template_file = os.path.join('matlab_templates', 'mex_sim_solver.in2.m')", ...
        '#', ...
        'Python SIM mex_sim_solver template');

    patch_line_content( ...
        path, ...
        "template_file = os.path.join('matlab_templates', 'make_mex_sim.in.m')", ...
        "template_file = os.path.join('matlab_templates', 'make_mex_sim.in2.m')", ...
        '#', ...
        'Python SIM make_mex_sim template');

    patch_line_content( ...
        path, ...
        "template_file = os.path.join('matlab_templates', 'make_sfun_sim.in.m')", ...
        "template_file = os.path.join('matlab_templates', 'make_sfun_sim.in2.m')", ...
        '#', ...
        'Python SIM make_sfun_sim template');
end


function patch_python_builder(path)

    require_file(path);
    backup_once(path);

    patch_line_content( ...
        path, ...
        "self.generator = 'Visual Studio 15 2017 Win64'", ...
        "self.generator = 'Visual Studio 17 2022'", ...
        '#', ...
        'Python Visual Studio generator');

    txt = fileread(path);

    if ~contains(txt, "self.host = 'x64'")

        [lines, eol] = split_lines(txt);

        found = false;

        for i = 1:numel(lines)

            if strcmp(strtrim(lines{i}), "self.generator = 'Visual Studio 17 2022'")

                indent = leading_whitespace(lines{i});

                % Keep every entry as a char vector. Mixing MATLAB string
                % scalars and char vectors makes strjoin() reject the cell array.
                lines = [ ...
                    lines(1:i), ...
                    {[indent, 'self.host = ''x64''']}, ...
                    lines(i+1:end) ...
                ];

                found = true;
                break;
            end
        end

        if ~found
            error('Could not insert Python CMakeBuilder x64 host.');
        end

        write_text_file(path, join_lines(lines, eol));

        fprintf('  [patched] Python Visual Studio x64 host\n');

    else

        fprintf('  [already patched] Python Visual Studio x64 host\n');
    end

    txt = fileread(path);
    [txt_lf, eol] = normalize_eol(txt);

    if ~contains( ...
            get_function_block(txt_lf, '    def get_cmd3_install(self):', '    def exec('), ...
            '--config Release')

        old_block = strjoin({ ...
            '    def get_cmd3_install(self):', ...
            '        return f''cmake --install "{self._build_dir}"''' ...
        }, newline);

        new_block = strjoin({ ...
            '    def get_cmd3_install(self):', ...
            '        # WINDOWS/MSVC PATCH: Visual Studio is multi-config.', ...
            '        if os.name == ''nt'':', ...
            '            return f''cmake --install "{self._build_dir}" --config Release''', ...
            '        return f''cmake --install "{self._build_dir}"''' ...
        }, newline);

        txt_lf = replace_once( ...
            txt_lf, ...
            old_block, ...
            new_block, ...
            'Python CMake install command');

        write_text_file(path, restore_eol(txt_lf, eol));

        fprintf('  [patched] Python CMake install --config Release\n');

    else

        fprintf('  [already patched] Python CMake install --config Release\n');
    end
end


function patch_compare_struct_to_json(path)

    require_file(path);
    backup_once(path);

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    marker = 'Only numeric/logical arrays are safe for subtraction.';

    if contains(txt, marker)
        fprintf('  [already patched] compare_struct_to_json numeric safety\n');
        return;
    end

    old = strjoin({ ...
        '    elseif ismatrix(ocp_data) && ismatrix(json_data)', ...
        '        diff_mask = abs(ocp_data - json_data) < tol;', ...
        '        if ~isequal(size(ocp_data), size(json_data))', ...
        '            mismatched{end+1} = path;', ...
        '        elseif ~all(diff_mask(:))', ...
        '            % check relative tolerance', ...
        '            rel_diff = abs(ocp_data - json_data) ./ max(abs(json_data), abs(ocp_data));', ...
        '            if ~all(rel_diff(:) < tol)', ...
        '                mismatched{end+1} = path;', ...
        '            end', ...
        '        end' ...
    }, newline);

    new = strjoin({ ...
        '    % WINDOWS/MSVC JSON/REUSE PATCH:', ...
        '    elseif (isnumeric(ocp_data) || islogical(ocp_data)) && ...', ...
        '           (isnumeric(json_data) || islogical(json_data))', ...
        '        % Only numeric/logical arrays are safe for subtraction.', ...
        '        if ~isequal(size(ocp_data), size(json_data))', ...
        '            mismatched{end+1} = path;', ...
        '            return;', ...
        '        end', ...
        '', ...
        '        a = double(ocp_data);', ...
        '        b = double(json_data);', ...
        '        abs_diff = abs(a - b);', ...
        '', ...
        '        if ~all(abs_diff(:) < tol)', ...
        '            scale = max(abs(a), abs(b));', ...
        '            rel_diff = zeros(size(abs_diff));', ...
        '            idx = scale > 0;', ...
        '            rel_diff(idx) = abs_diff(idx) ./ scale(idx);', ...
        '', ...
        '            if ~all(rel_diff(:) < tol)', ...
        '                mismatched{end+1} = path;', ...
        '            end', ...
        '        end' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old, ...
        new, ...
        'compare_struct_to_json numeric block');

    write_text_file(path, restore_eol(txt, eol));

    fprintf('  [patched] compare_struct_to_json numeric safety\n');
end


function patch_acados_sim_options(path)

    require_file(path);
    backup_once(path);

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    marker = '% WINDOWS/MSVC JSON/REUSE PATCH: AcadosSimOptions.from_struct';

    if contains(txt, marker)
        fprintf('  [already patched] AcadosSimOptions.from_struct\n');
        return;
    end

    block = strjoin({ ...
        '    methods (Static)', ...
        '        function obj = from_struct(s)', ...
        '            % WINDOWS/MSVC JSON/REUSE PATCH: AcadosSimOptions.from_struct', ...
        '            % Map serialized sim_method_* names back to MATLAB properties.', ...
        '', ...
        '            if ~isstruct(s)', ...
        '                error(''AcadosSimOptions.from_struct input must be a struct.'');', ...
        '            end', ...
        '', ...
        '            obj = AcadosSimOptions();', ...
        '', ...
        '            mapping = struct( ...', ...
        '                ''sim_method_num_stages'',  ''num_stages'', ...', ...
        '                ''sim_method_num_steps'',   ''num_steps'', ...', ...
        '                ''sim_method_newton_iter'', ''newton_iter'', ...', ...
        '                ''sim_method_newton_tol'',  ''newton_tol'', ...', ...
        '                ''sim_method_jac_reuse'',   ''jac_reuse'' ...', ...
        '            );', ...
        '', ...
        '            names = fieldnames(s);', ...
        '            for i = 1:numel(names)', ...
        '                source_name = names{i};', ...
        '', ...
        '                if isfield(mapping, source_name)', ...
        '                    target_name = mapping.(source_name);', ...
        '                else', ...
        '                    target_name = source_name;', ...
        '                end', ...
        '', ...
        '                if isprop(obj, target_name)', ...
        '                    obj.(target_name) = s.(source_name);', ...
        '                else', ...
        '                    warning( ...', ...
        '                        ''AcadosSimOptions.from_struct: ignoring unknown field "%s".'', ...', ...
        '                        source_name);', ...
        '                end', ...
        '            end', ...
        '        end', ...
        '    end', ...
        '', ...
        '' ...
    }, newline);

    starts = regexp(txt, '(?m)^end\s*$', 'start');

    if isempty(starts)
        error('Could not locate final AcadosSimOptions class end.');
    end

    insert_at = starts(end);

    txt = [ ...
        txt(1:insert_at-1), ...
        block, ...
        txt(insert_at:end) ...
    ];

    write_text_file(path, restore_eol(txt, eol));

    fprintf('  [patched] AcadosSimOptions.from_struct\n');
end


function patch_acados_sim_solver(path)

    require_file(path);
    backup_once(path);

    patch_line_content( ...
        path, ...
        "sim_struct_restore = loadjson(fileread(json_file), 'SimplifyCell', 0);", ...
        "sim_struct_restore = loadjson(fileread(obj.sim.code_gen_options.json_file), 'SimplifyCell', 0);", ...
        '%', ...
        'SIM reuse configured JSON filename');

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    if ~contains(txt, 'sim_solve_file = fullfile')

        old = "                obj.solver_creation_opts.compile_interface = ~exist(fullfile(obj.solver_creation_opts.output_dir, ['/sim_create', extension]), 'file');";

        new = strjoin({ ...
            '                % WINDOWS/MSVC JSON/REUSE PATCH:', ...
            '                % sim_compile_interface() creates sim_solve and sim_get.', ...
            '                sim_solve_file = fullfile(obj.solver_creation_opts.output_dir, [''sim_solve'', extension]);', ...
            '                sim_get_file = fullfile(obj.solver_creation_opts.output_dir, [''sim_get'', extension]);', ...
            '                obj.solver_creation_opts.compile_interface = ...', ...
            '                    ~(exist(sim_solve_file, ''file'') && exist(sim_get_file, ''file''));' ...
        }, newline);

        txt = replace_once( ...
            txt, ...
            char(old), ...
            new, ...
            'SIM generic MEX auto-detection');

        write_text_file(path, restore_eol(txt, eol));

        fprintf('  [patched] SIM generic MEX auto-detection\n');

    else

        fprintf('  [already patched] SIM generic MEX auto-detection\n');
    end

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    if ~contains(txt, 'WINDOWS/MSVC REUSE ARTIFACT CHECK: SIM')

        marker = strjoin({ ...
            '            if ~exist(obj.sim.code_gen_options.json_file, ''file'')', ...
            '                code_reuse_possible = 0;', ...
            '                if verbose', ...
            '                    disp(''code reuse not possible: json file does not exist'');', ...
            '                end', ...
            '                return;', ...
            '            end' ...
        }, newline);

        patch = [ ...
            marker, ...
            newline, ...
            newline, ...
            strjoin({ ...
                '            % WINDOWS/MSVC REUSE ARTIFACT CHECK: SIM', ...
                '            % Reject reuse if a previous generation stopped before', ...
                '            % creating all problem-specific artifacts.', ...
                '            if ispc', ...
                '                export_dir = obj.sim.code_gen_options.code_export_directory;', ...
                '                wrapper_file = fullfile(export_dir, [obj.sim.name ''_mex_sim_solver.m'']);', ...
                '                solver_dll = fullfile(export_dir, [''acados_sim_solver_'' obj.sim.name ''.dll'']);', ...
                '                solver_lib = fullfile(export_dir, [''acados_sim_solver_'' obj.sim.name ''.lib'']);', ...
                '', ...
                '                if ~exist(wrapper_file, ''file'') || ...', ...
                '                        ~exist(solver_dll, ''file'') || ~exist(solver_lib, ''file'')', ...
                '                    code_reuse_possible = 0;', ...
                '                    if verbose', ...
                '                        disp(''code reuse not possible: generated SIM artifacts are incomplete'');', ...
                '                    end', ...
                '                    return;', ...
                '                end', ...
                '            end' ...
            }, newline) ...
        ];

        txt = replace_once( ...
            txt, ...
            marker, ...
            patch, ...
            'SIM reuse artifact completeness check');

        write_text_file(path, restore_eol(txt, eol));

        fprintf('  [patched] SIM reuse artifact completeness check\n');

    else

        fprintf('  [already patched] SIM reuse artifact completeness check\n');
    end
end


function patch_acados_sim_to_struct(path)

    require_file(path);
    backup_once(path);

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    marker = 'before dereferencing properties to avoid triggering its warning.';

    if contains(txt, marker)
        fprintf('  [already patched] AcadosSim code_gen_opts serialization warning\n');
        return;
    end

    old = strjoin({ ...
        '            s = struct();', ...
        '            for fi = 1:numel(publicProperties)' ...
    }, newline);

    new = strjoin({ ...
        '            % WINDOWS/MSVC JSON/REUSE PATCH:', ...
        '            % code_gen_opts is a deprecated dependent property. Remove it', ...
        '            % before dereferencing properties to avoid triggering its warning.', ...
        '            publicProperties = setdiff(publicProperties, {''code_gen_opts''}, ''stable'');', ...
        '', ...
        '            s = struct();', ...
        '            for fi = 1:numel(publicProperties)' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old, ...
        new, ...
        'AcadosSim code_gen_opts serialization');

    write_text_file(path, restore_eol(txt, eol));

    fprintf('  [patched] AcadosSim code_gen_opts serialization warning\n');
end


function patch_acados_codegen_options(path)

    require_file(path);
    backup_once(path);

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    if contains(txt, 'head_abs = absolute_path(head);')
        fprintf('  [already patched] repeated json_file path warning\n');
        return;
    end

    old = strjoin({ ...
        '                [head, tail, ext] = fileparts(obj.json_file);', ...
        '                if ~isempty(head)', ...
        '                    warning([''A path is provided for json_file. This is not supported. The json file will be written to the code_export_directory '' obj.code_export_directory '' instead.''])', ...
        '                end', ...
        '                obj.json_file = fullfile(obj.code_export_directory, strcat(tail, ext));' ...
    }, newline);

    new = strjoin({ ...
        '                [head, tail, ext] = fileparts(obj.json_file);', ...
        '                if ~isempty(head)', ...
        '                    % WINDOWS/MSVC JSON/REUSE PATCH:', ...
        '                    % Do not warn when this is already the normalized export path.', ...
        '                    head_abs = absolute_path(head);', ...
        '                    if ~strcmpi(head_abs, obj.code_export_directory)', ...
        '                        warning([''A path is provided for json_file. This is not supported. The json file will be written to the code_export_directory '' obj.code_export_directory '' instead.''])', ...
        '                    end', ...
        '                end', ...
        '                obj.json_file = fullfile(obj.code_export_directory, strcat(tail, ext));' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old, ...
        new, ...
        'AcadosCodeGenOptions repeated json warning');

    write_text_file(path, restore_eol(txt, eol));

    fprintf('  [patched] repeated json_file path warning\n');
end


function patch_acados_ocp_solver(path)

    require_file(path);
    backup_once(path);

    txt = fileread(path);
    [txt, eol] = normalize_eol(txt);

    if contains(txt, 'WINDOWS/MSVC REUSE ARTIFACT CHECK: OCP')
        fprintf('  [already patched] OCP reuse artifact completeness check\n');
        return;
    end

    marker = strjoin({ ...
        '            if ~exist(json_file, ''file'')', ...
        '                code_reuse_possible = 0;', ...
        '                if verbose', ...
        '                    disp(''code reuse not possible: json file does not exist'');', ...
        '                end', ...
        '                return;', ...
        '            end' ...
    }, newline);

    patch = [ ...
        marker, ...
        newline, ...
        newline, ...
        strjoin({ ...
            '            % WINDOWS/MSVC REUSE ARTIFACT CHECK: OCP', ...
            '            if ispc', ...
            '                export_dir = obj.ocp.code_gen_options.code_export_directory;', ...
            '                wrapper_file = fullfile(export_dir, [obj.ocp.name ''_mex_solver.m'']);', ...
            '                solver_dll = fullfile(export_dir, [''acados_ocp_solver_'' obj.ocp.name ''.dll'']);', ...
            '                solver_lib = fullfile(export_dir, [''acados_ocp_solver_'' obj.ocp.name ''.lib'']);', ...
            '                mex_create = fullfile(export_dir, [''acados_mex_create_'' obj.ocp.name ''.'' mexext]);', ...
            '', ...
            '                if ~exist(wrapper_file, ''file'') || ...', ...
            '                        ~exist(solver_dll, ''file'') || ...', ...
            '                        ~exist(solver_lib, ''file'') || ...', ...
            '                        ~exist(mex_create, ''file'')', ...
            '                    code_reuse_possible = 0;', ...
            '                    if verbose', ...
            '                        disp(''code reuse not possible: generated OCP artifacts are incomplete'');', ...
            '                    end', ...
            '                    return;', ...
            '                end', ...
            '            end' ...
        }, newline) ...
    ];

    txt = replace_once( ...
        txt, ...
        marker, ...
        patch, ...
        'OCP reuse artifact completeness check');

    write_text_file(path, restore_eol(txt, eol));

    fprintf('  [patched] OCP reuse artifact completeness check\n');
end


function derive_msvc_installer(src, dst)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    txt = replace_once( ...
        txt, ...
        'function acados_install_windows(varargin)', ...
        'function acados_install_windows_msvc(varargin)', ...
        'MSVC installer function name');

    txt = replace_once( ...
        txt, ...
        "    acadosBuildPath=fullfile(acadosPath,'build');", ...
        strjoin({ ...
            '    % WINDOWS/MSVC PATCH: dedicated Visual Studio build tree.', ...
            '    acadosBuildPath=fullfile(acadosPath,''build_msvc'');' ...
        }, newline), ...
        'MSVC installer build directory');

    old_compiler = strjoin({ ...
        '    % Read the mex C compiler configuration and extract the location', ...
        '    cCompilerConfig = mex.getCompilerConfigurations(''C'');', ...
        '    pathToCompilerLocation = cCompilerConfig.Location;', ...
        '    % Modify the environment PATH variable for this MATLAB session such that', ...
        '    % the mex C compiler takes priority ensuring calls to gcc uses the', ...
        '    % configured mex compiler', ...
        '    setenv(''PATH'', [fullfile(pathToCompilerLocation,''bin'') '';'' origEnvPath]);' ...
    }, newline);

    new_compiler = strjoin({ ...
        '    % WINDOWS/MSVC PATCH:', ...
        '    % Visual Studio generator finds MSVC itself; do not prepend MinGW paths.', ...
        '    cCompilerConfig = mex.getCompilerConfigurations(''C'', ''Selected'');', ...
        '    if isempty(cCompilerConfig)', ...
        '        warning(''No MATLAB C compiler selected. Run "mex -setup C".'');', ...
        '    else', ...
        '        fprintf(''MATLAB selected C compiler: %s\n'', cCompilerConfig.Name);', ...
        '        if ~contains(lower(cCompilerConfig.Name), ''microsoft'')', ...
        '            warning(''Select Microsoft Visual C++ with "mex -setup C".'');', ...
        '        end', ...
        '    end' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        old_compiler, ...
        new_compiler, ...
        'MSVC installer compiler handling');

    old_cmake = "    cmake_cmd = sprintf('cmake.exe -G ""MinGW Makefiles"" -DACADOS_INSTALL_DIR=%%ACADOS_INSTALL_DIR%% %s ..',cmakeConfigString);";

    new_cmake = strjoin({ ...
        '    % WINDOWS/MSVC PATCH: Visual Studio 2022 x64, /MD, GENERIC targets.', ...
        '    cmake_cmd = sprintf([ ...', ...
        '        ''cmake -G "Visual Studio 17 2022" -A x64 '', ...', ...
        '        ''-DCMAKE_POLICY_DEFAULT_CMP0091=NEW '', ...', ...
        '        ''-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL '', ...', ...
        '        ''-DBLASFEO_TARGET=GENERIC -DHPIPM_TARGET=GENERIC '', ...', ...
        '        ''-DACADOS_INSTALL_DIR="%s" %s ..'' ...', ...
        '    ], acadosPath, cmakeConfigString);' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        char(old_cmake), ...
        new_cmake, ...
        'MSVC installer CMake command');

    txt = replace_once( ...
        txt, ...
        strjoin({ ...
            '    fprintf(''Compiling and installing using minGW\n'');', ...
            '', ...
            '    compile_command=''mingw32-make.exe -j4'';' ...
        }, newline), ...
        strjoin({ ...
            '    fprintf(''Compiling and installing using MSVC\n'');', ...
            '', ...
            '    compile_command=''cmake --build . --parallel 4 --config Release'';' ...
        }, newline), ...
        'MSVC installer build command');

    txt = replace_once( ...
        txt, ...
        "    install_command='mingw32-make.exe install';", ...
        "    install_command='cmake --install . --config Release';", ...
        'MSVC installer install command');

    txt = replace_once( ...
        txt, ...
        strjoin({ ...
            '    run(''acados_env_variables_windows'');', ...
            '    check_acados_requirements(true);' ...
        }, newline), ...
        strjoin({ ...
            '    run(''acados_env_variables_windows'');', ...
            '', ...
            '    % WINDOWS/MSVC PATCH: put installed DLLs on this MATLAB PATH.', ...
            '    acados_bin = fullfile(acadosPath, ''bin'');', ...
            '    path_entries = strsplit(getenv(''PATH''), pathsep);', ...
            '    if ~any(strcmpi(path_entries, acados_bin))', ...
            '        setenv(''PATH'', [acados_bin, pathsep, getenv(''PATH'')]);', ...
            '    end', ...
            '', ...
            '    check_acados_requirements(false);' ...
        }, newline), ...
        'MSVC installer MATLAB environment');

    txt = strrep( ...
        txt, ...
        '% acados_install_windows([CmakeConfigString])', ...
        strjoin({ ...
            '% acados_install_windows_msvc([CmakeConfigString])', ...
            '% Local Windows/MSVC derivative of upstream acados_install_windows.m' ...
        }, newline));

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function derive_shared_static_msvc_installer(src, dst)

    require_file(src);

    txt = fileread(src);
    [txt, eol] = normalize_eol(txt);

    txt = replace_once( ...
        txt, ...
        'function acados_install_shared_and_static_windows(varargin)', ...
        'function acados_install_shared_and_static_windows_msvc(varargin)', ...
        'shared/static installer function name');

    txt = strrep( ...
        txt, ...
        'acados_install_windows(', ...
        'acados_install_windows_msvc(');

    marker = strjoin({ ...
        '    acados_lib_path = fullfile(acados_root_dir, "lib");', ...
        '    [status, message ] = movefile(fullfile(acados_lib_path, ''*.lib''), acados_bin_path);' ...
    }, newline);

    replacement = strjoin({ ...
        '    acados_lib_path = fullfile(acados_root_dir, "lib");', ...
        '', ...
        '    % WINDOWS/MSVC PATCH:', ...
        '    % Optional backend DLLs may remain under build_msvc/Release.', ...
        '    acados_build_path = fullfile(acados_root_dir, ''build_msvc'');', ...
        '    optional_solver_dlls = {''qpOASES_e.dll'', ''qpdunes.dll''};', ...
        '', ...
        '    for i = 1:numel(optional_solver_dlls)', ...
        '        matches = dir(fullfile(acados_build_path, ''**'', optional_solver_dlls{i}));', ...
        '        if ~isempty(matches)', ...
        '            src_dll = fullfile(matches(1).folder, matches(1).name);', ...
        '            dst_dll = fullfile(acados_bin_path, matches(1).name);', ...
        '            fprintf(''Copying optional solver DLL: %s\n'', matches(1).name);', ...
        '            copyfile(src_dll, dst_dll, ''f'');', ...
        '        end', ...
        '    end', ...
        '', ...
        '    % Shared-build .lib files are import libraries on Windows.', ...
        '    [status, message ] = movefile(fullfile(acados_lib_path, ''*.lib''), acados_bin_path);' ...
    }, newline);

    txt = replace_once( ...
        txt, ...
        marker, ...
        replacement, ...
        'shared/static optional DLL handling');

    write_text_file(dst, restore_eol(txt, eol));

    fprintf('  generated: %s\n', dst);
end


function write_manifest(acados_root)

    manifest = fullfile( ...
        acados_root, ...
        '.acados_windows_msvc_patch_manifest.txt');

    fid = fopen(manifest, 'w');

    if fid == -1
        warning('Could not write manifest file.');
        return;
    end

    c = onCleanup(@() fclose(fid));

    fprintf(fid, 'acados Windows/MSVC pure MATLAB bootstrap\n');
    fprintf(fid, 'Generated: %s\n', char(datetime('now')));
    fprintf(fid, 'Root: %s\n', acados_root);

    git_cmd = sprintf('git -C "%s" rev-parse HEAD', acados_root);
    [status, commit] = system(git_cmd);

    if status == 0
        fprintf(fid, 'Git commit: %s\n', strtrim(commit));
    else
        fprintf(fid, 'Git commit: unavailable\n');
    end

    fprintf(fid, '\nGenerated derivative templates:\n');

    fprintf(fid, '  CMakeLists.in2.txt\n');
    fprintf(fid, '  make_mex.in2.m\n');
    fprintf(fid, '  make_mex_sim.in2.m\n');
    fprintf(fid, '  make_sfun.in2.m\n');
    fprintf(fid, '  make_sfun_sim.in2.m\n');
    fprintf(fid, '  mex_sim_solver.in2.m\n');

    clear c;
end


function patch_line_content(path, original_core, replacement_core, comment_char, label)

    original_core = char(original_core);
    replacement_core = char(replacement_core);

    txt = fileread(path);

    [lines, eol] = split_lines(txt);

    for i = 1:numel(lines)
        if strcmp(strtrim(lines{i}), strtrim(replacement_core))
            fprintf('  [already patched] %s\n', label);
            return;
        end
    end

    found = false;

    for i = 1:numel(lines)

        if strcmp(strtrim(lines{i}), strtrim(original_core))

            indent = leading_whitespace(lines{i});

            replacement = { ...
                [indent, comment_char, ' WINDOWS/MSVC PATCH - upstream line retained:'], ...
                [indent, comment_char, ' ', strtrim(original_core)], ...
                [indent, strtrim(replacement_core)] ...
            };

            lines = [ ...
                lines(1:i-1), ...
                replacement, ...
                lines(i+1:end) ...
            ];

            found = true;
            break;
        end
    end

    if ~found
        error( ...
            'Could not locate upstream line for %s in:\n  %s', ...
            label, ...
            path);
    end

    write_text_file(path, join_lines(lines, eol));

    fprintf('  [patched] %s\n', label);
end


function backup_once(path)

    backup = [path, '.pre_windows_bootstrap.bak'];

    if ~isfile(backup)
        copyfile(path, backup);
        fprintf('  backup: %s\n', backup);
    end
end


function require_file(path)

    if ~isfile(path)
        error('Required file not found:\n  %s', path);
    end
end


function out = replace_once(txt, old, new, label)

    % Work internally with character vectors so this helper behaves the same
    % whether its caller supplied MATLAB string scalars or char vectors.
    old = char(old);
    new = char(new);

    hits = strfind(txt, old);

    if isempty(hits)
        error('Could not locate expected upstream code for: %s', label);
    end

    idx = hits(1);

    out = [ ...
        txt(1:idx-1), ...
        new, ...
        txt(idx+length(old):end) ...
    ];
end


function [txt_lf, eol] = normalize_eol(txt)

    if contains(txt, sprintf('\r\n'))
        eol = sprintf('\r\n');
    else
        eol = sprintf('\n');
    end

    txt_lf = strrep( ...
        txt, ...
        sprintf('\r\n'), ...
        sprintf('\n'));
end


function txt = restore_eol(txt_lf, eol)

    if strcmp(eol, sprintf('\r\n'))
        txt = strrep( ...
            txt_lf, ...
            sprintf('\n'), ...
            sprintf('\r\n'));
    else
        txt = txt_lf;
    end
end


function write_text_file(path, txt)

    fid = fopen(path, 'w');

    if fid == -1
        error('Could not open file for writing:\n  %s', path);
    end

    c = onCleanup(@() fclose(fid));

    fwrite(fid, txt, 'char');

    clear c;
end


function idx = find_final_function_end(txt)

    starts = regexp(txt, '(?m)^end\s*$', 'start');

    if isempty(starts)
        error('Could not locate final function end.');
    end

    idx = starts(end);
end


function [lines, eol] = split_lines(txt)

    if contains(txt, sprintf('\r\n'))
        eol = sprintf('\r\n');
        txt = strrep(txt, sprintf('\r\n'), sprintf('\n'));
    else
        eol = sprintf('\n');
    end

    lines = regexp(txt, '\n', 'split');

    if ~isempty(lines) && isempty(lines{end})
        lines(end) = [];
    end
end


function txt = join_lines(lines, eol)

    txt = strjoin(lines, eol);

    txt = [txt, eol];
end


function ws = leading_whitespace(line)

    ws = regexp(line, '^\s*', 'match', 'once');

    if isempty(ws)
        ws = '';
    end
end


function block = get_function_block(txt, start_marker, end_marker)

    i0 = strfind(txt, start_marker);
    i1 = strfind(txt, end_marker);

    if isempty(i0) || isempty(i1)
        block = '';
        return;
    end

    i0 = i0(1);
    i1 = i1(find(i1 > i0, 1, 'first'));

    if isempty(i1)
        block = '';
        return;
    end

    block = txt(i0:i1-1);
end
