%% apply_acados_json_matlab_patches.m
% Apply the small MATLAB JSON / struct compatibility fixes used by this
% local acados workflow.
%
% Run from:
%   <acados>\interfaces\acados_matlab_octave
%
% Patches:
%   compare_struct_to_json.m
%   AcadosSimOptions.m
%   AcadosSimSolver.m
%
% This script is separate from the larger Windows/MSVC patcher.
% Backups use suffix: .pre_json_patch.bak

clearvars;
clc;

fprintf('acados MATLAB JSON/struct patcher\n');
fprintf('=================================\n\n');

matlab_dir = pwd;
[interfaces_dir, current_name] = fileparts(matlab_dir);
[~, interfaces_name] = fileparts(interfaces_dir);

if ~strcmp(current_name, 'acados_matlab_octave') || ...
        ~strcmp(interfaces_name, 'interfaces')
    error(['Run this script from:\n', ...
           '  <acados>\\interfaces\\acados_matlab_octave\n']);
end

compare_file = fullfile(matlab_dir, 'compare_struct_to_json.m');
sim_options_file = fullfile(matlab_dir, 'AcadosSimOptions.m');
sim_solver_file = fullfile(matlab_dir, 'AcadosSimSolver.m');

%% Patch 1: compare_struct_to_json.m
txt = fileread(compare_file);
backup_once(compare_file);

if ~contains(txt, 'Only perform subtraction for numeric/logical arrays')
    old = sprintf([ ...
        '    elseif ismatrix(ocp_data) && ismatrix(json_data)\n' ...
        '        diff_mask = abs(ocp_data - json_data) < tol;\n' ...
        '        if ~isequal(size(ocp_data), size(json_data))\n' ...
        '            mismatched{end+1} = path;\n' ...
        '        elseif ~all(diff_mask(:))\n' ...
        '            %% check relative tolerance\n' ...
        '            rel_diff = abs(ocp_data - json_data) ./ max(abs(json_data), abs(ocp_data));\n' ...
        '            if ~all(rel_diff(:) < tol)\n' ...
        '                mismatched{end+1} = path;\n' ...
        '            end\n' ...
        '        end' ...
    ]);

    new = sprintf([ ...
        '    %% JSON/STRUCT PATCH - original upstream block retained:\n' ...
        '    %% elseif ismatrix(ocp_data) && ismatrix(json_data)\n' ...
        '        %% diff_mask = abs(ocp_data - json_data) < tol;\n' ...
        '        %% if ~isequal(size(ocp_data), size(json_data))\n' ...
        '            %% mismatched{end+1} = path;\n' ...
        '        %% elseif ~all(diff_mask(:))\n' ...
        '            %% %% check relative tolerance\n' ...
        '            %% rel_diff = abs(ocp_data - json_data) ./ max(abs(json_data), abs(ocp_data));\n' ...
        '            %% if ~all(rel_diff(:) < tol)\n' ...
        '                %% mismatched{end+1} = path;\n' ...
        '            %% end\n' ...
        '        %% end\n' ...
        '    elseif (isnumeric(ocp_data) || islogical(ocp_data)) && ...\n' ...
        '           (isnumeric(json_data) || islogical(json_data))\n' ...
        '        %% JSON/STRUCT PATCH:\n' ...
        '        %% Only perform subtraction for numeric/logical arrays. MATLAB''s\n' ...
        '        %% ismatrix() is a dimensionality test and does not guarantee that\n' ...
        '        %% the operands support subtraction.\n' ...
        '\n' ...
        '        if ~isequal(size(ocp_data), size(json_data))\n' ...
        '            mismatched{end+1} = path;\n' ...
        '            return;\n' ...
        '        end\n' ...
        '\n' ...
        '        a = double(ocp_data);\n' ...
        '        b = double(json_data);\n' ...
        '        abs_diff = abs(a - b);\n' ...
        '\n' ...
        '        if ~all(abs_diff(:) < tol)\n' ...
        '            scale = max(abs(a), abs(b));\n' ...
        '            rel_diff = zeros(size(abs_diff));\n' ...
        '            idx = scale > 0;\n' ...
        '            rel_diff(idx) = abs_diff(idx) ./ scale(idx);\n' ...
        '            if ~all(rel_diff(:) < tol)\n' ...
        '                mismatched{end+1} = path;\n' ...
        '            end\n' ...
        '        end' ...
    ]);

    txt = replace_exact_normalized(txt, old, new, 'compare_struct_to_json numeric block');
    write_text(compare_file, txt);
    fprintf('[patched] compare_struct_to_json.m\n');
else
    fprintf('[already patched] compare_struct_to_json.m\n');
end

%% Patch 2: AcadosSimOptions.from_struct()
txt = fileread(sim_options_file);
backup_once(sim_options_file);

marker = '% JSON/STRUCT PATCH: AcadosSimOptions.from_struct';

if ~contains(txt, marker)
    static_block = sprintf([ ...
        '\n    methods (Static)\n' ...
        '        function obj = from_struct(s)\n' ...
        '            %% JSON/STRUCT PATCH: AcadosSimOptions.from_struct\n' ...
        '            %% Map JSON sim_method_* names back to MATLAB properties.\n' ...
        '\n' ...
        '            if ~isstruct(s)\n' ...
        '                error(''AcadosSimOptions.from_struct input must be a struct.'');\n' ...
        '            end\n' ...
        '\n' ...
        '            obj = AcadosSimOptions();\n' ...
        '            json_to_property = struct( ...\n' ...
        '                ''sim_method_num_stages'',  ''num_stages'', ...\n' ...
        '                ''sim_method_num_steps'',   ''num_steps'', ...\n' ...
        '                ''sim_method_newton_iter'', ''newton_iter'', ...\n' ...
        '                ''sim_method_newton_tol'',  ''newton_tol'', ...\n' ...
        '                ''sim_method_jac_reuse'',   ''jac_reuse'' ...\n' ...
        '            );\n' ...
        '\n' ...
        '            fields = fieldnames(s);\n' ...
        '            for i = 1:numel(fields)\n' ...
        '                source_name = fields{i};\n' ...
        '                if isfield(json_to_property, source_name)\n' ...
        '                    target_name = json_to_property.(source_name);\n' ...
        '                else\n' ...
        '                    target_name = source_name;\n' ...
        '                end\n' ...
        '\n' ...
        '                if isprop(obj, target_name)\n' ...
        '                    obj.(target_name) = s.(source_name);\n' ...
        '                else\n' ...
        '                    warning(''AcadosSimOptions.from_struct: ignoring unknown field "%%s".'', source_name);\n' ...
        '                end\n' ...
        '            end\n' ...
        '        end\n' ...
        '    end\n' ...
    ]);

    txtn = normalize_lf(txt);
    closing = sprintf('    end\nend\n');
    hits = strfind(txtn, closing);
    if isempty(hits)
        error('Could not locate final AcadosSimOptions class ending.');
    end

    idx = hits(end) + length(sprintf('    end\n')) - 1;
    txtn = [txtn(1:idx), static_block, txtn(idx+1:end)];
    write_text(sim_options_file, restore_eol(txt, txtn));
    fprintf('[patched] AcadosSimOptions.m\n');
else
    fprintf('[already patched] AcadosSimOptions.m\n');
end

%% Patch 3: AcadosSimSolver.m undefined json_file
txt = fileread(sim_solver_file);
backup_once(sim_solver_file);

if ~contains(txt, 'fileread(obj.sim.code_gen_options.json_file)')
    old = ...
        "                sim_struct_restore = loadjson(fileread(json_file), 'SimplifyCell', 0);";

    new = sprintf([ ...
        '                %% JSON/STRUCT PATCH - original upstream line retained:\n' ...
        '                %% sim_struct_restore = loadjson(fileread(json_file), ''SimplifyCell'', 0);\n' ...
        '                %% Use the configured SIM JSON file; "json_file" is undefined here upstream.\n' ...
        '                sim_struct_restore = loadjson( ...\n' ...
        '                    fileread(obj.sim.code_gen_options.json_file), ...\n' ...
        '                    ''SimplifyCell'', 0);' ...
    ]);

    txt = replace_exact_normalized(txt, char(old), new, 'AcadosSimSolver JSON file line');
    write_text(sim_solver_file, txt);
    fprintf('[patched] AcadosSimSolver.m\n');
else
    fprintf('[already patched] AcadosSimSolver.m\n');
end

fprintf('\nDone. Backups use suffix .pre_json_patch.bak\n');


%% Local functions

function backup_once(filename)
    backup = [filename, '.pre_json_patch.bak'];
    if ~isfile(backup)
        copyfile(filename, backup);
    end
end

function out = normalize_lf(in)
    out = strrep(in, sprintf('\r\n'), sprintf('\n'));
end

function out = restore_eol(original, normalized)
    if contains(original, sprintf('\r\n'))
        out = strrep(normalized, sprintf('\n'), sprintf('\r\n'));
    else
        out = normalized;
    end
end

function out = replace_exact_normalized(txt, old, new, label)
    txtn = normalize_lf(txt);
    oldn = normalize_lf(old);
    newn = normalize_lf(new);

    if ~contains(txtn, oldn)
        error('Could not find expected upstream code for: %s', label);
    end

    outn = strrep(txtn, oldn, newn);
    out = restore_eol(txt, outn);
end

function write_text(filename, txt)
    fid = fopen(filename, 'w');
    if fid == -1
        error('Could not open file for writing: %s', filename);
    end
    c = onCleanup(@() fclose(fid));
    fwrite(fid, txt, 'char');
    clear c;
end
